name: Z-Wave.Me Add-on
startup: services
version: 1.1.2
slug: zwave_me_server
description: 'Z-Wave.Me Add-on for HAss'
arch:
  - amd64
  - aarch64
  - armhf
url: https://github.com/z-wave-me/addon-zwave-me
ports:
  8083/tcp: 8083
  8084/tcp: 8084
devices:
  - /dev/ttyACM0
webui: http://[HOST]:[PORT:8083]
ports_description:
  8083/tcp: Z-Way UI
  8084/tcp: Webif UI
image: "ghcr.io/z-wave-me/{arch}-ha-z-wave-me-addon"
volumes:
  - /etc/timezone:/etc/timezone:ro
  - /etc/localtime:/etc/localtime:ro
